name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"
      - ".editorconfig"
      - ".gitignore"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**/*.md"
      - ".editorconfig"
      - ".gitignore"

jobs:
  test:
    name: Run Mix Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.18"
          otp-version: "27.x"

      - name: Install minimal stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Restore Mix Dependency Cache
        id: cache-mix-deps
        uses: actions/cache@v3
        with:
          path: |
            ./deps
            ./_build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Install Mix Dependencies
        if: steps.cache-mix-deps.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.clean --all
          mix deps.get
          mix deps.compile

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Check For Unused Dependencies
        run: mix deps.unlock --check-unused

      - run: mix deps.compile
        env:
          HUMAN_NAME_BUILD: 1

      - run: mix compile --warnings-as-errors
        env:
          HUMAN_NAME_BUILD: 1
          MIX_ENV: test

      - name: Run Tests
        run: HUMAN_NAME_BUILD=1 mix coveralls.github
        env:
          MIX_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
